#!/usr/bin/env python3
"""Portable controller for DLSS Bridge.

The controller only writes beneath the project root. Launch frontends call it
to resolve policy and produce diagnostics; frame data remains in-process.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import tomllib
from typing import Any

ROOT = Path(__file__).resolve().parent.parent


def inside_root(path: Path) -> Path:
    resolved = path.expanduser().resolve()
    try:
        resolved.relative_to(ROOT)
    except ValueError as exc:
        raise SystemExit(f"refusing to write outside project root {ROOT}: {resolved}") from exc
    return resolved


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    result = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = value
    return result


def bool_int(value: Any) -> int:
    if isinstance(value, bool):
        return int(value)
    if value in (0, 1):
        return int(value)
    raise SystemExit(f"expected boolean, got {value!r}")


def resolved_runtime(data: dict[str, Any]) -> dict[str, str | int]:
    execution = data.get("execution", {})
    transport = data.get("transport", {})
    timing = data.get("timing", {})
    bridge = data.get("bridge", {})
    mode = execution.get("mode", "auto")
    if mode not in ("auto", "same_gpu", "secondary_gpu"):
        raise SystemExit(f"invalid execution.mode: {mode}")
    selector = str(execution.get("compute_adapter", "auto"))
    if not (selector in ("auto", "game") or selector.startswith(("index:", "luid:", "uuid:", "pci:"))):
        raise SystemExit(f"invalid execution.compute_adapter: {selector}")
    require = bool_int(execution.get("require_neural_result", True))
    if require != 1:
        raise SystemExit("require_neural_result=false is unsupported by project policy")
    slots = int(transport.get("ring_slots", 3))
    if not 2 <= slots <= 8:
        raise SystemExit("transport.ring_slots must be between 2 and 8")
    budget = int(transport.get("latency_budget_ms", timing.get("latency_budget_ms", 16)))
    output_transport = str(transport.get("output_format", "native"))
    if output_transport not in ("native", "r11g11b10_float"):
        raise SystemExit(f"invalid transport.output_format: {output_transport}")
    neural_queue_mode = str(transport.get("neural_queue", "split"))
    if neural_queue_mode not in ("split", "unified"):
        raise SystemExit(f"invalid transport.neural_queue: {neural_queue_mode}")
    if budget <= 0:
        raise SystemExit("latency budget must be positive")
    return {
        "mode": int(bridge.get("mode", 0)),
        "flags": int(bridge.get("flags", -1)),
        "subrects": bool_int(bridge.get("subrects", True)),
        "verbose": bool_int(bridge.get("verbose", False)),
        "sync": 1,
        "execution_mode": mode,
        "compute_adapter": selector,
        "require_neural_result": 1,
        "ring_slots": slots,
        "latency_budget_ms": budget,
        "output_transport": output_transport,
        "neural_queue_mode": neural_queue_mode,
    }


def write_runtime(settings: dict[str, str | int], output: Path) -> None:
    output = inside_root(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    body = "# generated by controller/dlss_bridge.py; neural-only policy\n"
    body += "".join(f"{key}={value}\n" for key, value in settings.items())
    output.write_text(body)


def cmd_resolve(args: argparse.Namespace) -> int:
    data = load_toml(Path(args.config))
    for profile in args.profile:
        data = merge(data, load_toml(Path(profile)))
    write_runtime(resolved_runtime(data), Path(args.output))
    print(Path(args.output).expanduser().resolve())
    return 0


def gpu_inventory() -> list[dict[str, Any]]:
    fields = ["index", "uuid", "pci.bus_id", "name", "driver_version"]
    command = ["nvidia-smi", f"--query-gpu={','.join(fields)}", "--format=csv,noheader,nounits"]
    try:
        completed = subprocess.run(command, text=True, capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        return [{"available": False, "error": str(exc)}]
    rows = []
    for line in completed.stdout.splitlines():
        values = [part.strip() for part in line.split(",", len(fields) - 1)]
        if len(values) == len(fields):
            rows.append(dict(zip(fields, values)) | {"available": True})
    return rows


def component_inventory() -> list[dict[str, Any]]:
    components: list[dict[str, Any]] = []
    for group in ("hosts", "capture", "executors", "transports", "platform"):
        for manifest in sorted((ROOT / group).glob("*/backend.toml")):
            item = load_toml(manifest)
            for required in ("schema", "kind", "id", "state"):
                if required not in item:
                    raise SystemExit(f"{manifest}: missing {required}")
            item["manifest"] = str(manifest.relative_to(ROOT))
            components.append(item)
    return components


def cmd_components(args: argparse.Namespace) -> int:
    print(json.dumps({"schema": 1, "components": component_inventory()}, indent=2))
    return 0


def cmd_probe(args: argparse.Namespace) -> int:
    report = {
        "schema": 1,
        "controller": "portable-dlss-bridge",
        "platform": sys.platform,
        "gpus": gpu_inventory(),
        "notes": [
            "GPU series is informational; runtime feature and transport probes decide support.",
            "DXGI LUID correlation is completed by the in-process Windows/Proton runtime.",
        ],
    }
    encoded = json.dumps(report, indent=2) + "\n"
    if args.output:
        output = inside_root(Path(args.output))
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(encoded)
    print(encoded, end="")
    return 0


def cmd_launch(args: argparse.Namespace) -> int:
    if not args.command:
        raise SystemExit("launch requires a command after --")
    output = ROOT / "runtime" / "resolved" / f"{args.frontend}.cfg"
    data = load_toml(Path(args.config))
    for profile in args.profile:
        data = merge(data, load_toml(Path(profile)))
    write_runtime(resolved_runtime(data), output)
    env = os.environ.copy()
    env["DLSS_BRIDGE_CONFIG"] = str(output)
    env["DLSS_BRIDGE_FRONTEND"] = args.frontend
    if args.dry_run:
        print(json.dumps({"config": str(output), "frontend": args.frontend, "command": args.command}, indent=2))
        return 0
    os.execvpe(args.command[0], args.command, env)
    return 127


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser()
    commands = result.add_subparsers(dest="subcommand", required=True)
    resolve = commands.add_parser("resolve")
    resolve.add_argument("--config", default=str(ROOT / "profiles" / "default.toml"))
    resolve.add_argument("--profile", action="append", default=[])
    resolve.add_argument("--output", required=True)
    resolve.set_defaults(func=cmd_resolve)
    components = commands.add_parser("components")
    components.set_defaults(func=cmd_components)
    probe = commands.add_parser("probe")
    probe.add_argument("--output")
    probe.set_defaults(func=cmd_probe)
    launch = commands.add_parser("launch")
    launch.add_argument("--frontend", choices=("desktop", "steam-proton", "sunshine"), required=True)
    launch.add_argument("--config", default=str(ROOT / "profiles" / "default.toml"))
    launch.add_argument("--profile", action="append", default=[])
    launch.add_argument("--dry-run", action="store_true")
    launch.add_argument("command", nargs=argparse.REMAINDER)
    launch.set_defaults(func=cmd_launch)
    return result


if __name__ == "__main__":
    parsed = parser().parse_args()
    if parsed.subcommand == "launch" and parsed.command[:1] == ["--"]:
        parsed.command = parsed.command[1:]
    raise SystemExit(parsed.func(parsed))
